name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, , macos-latest]
        ruby: ['2.7', '3.0', '3.1', 'head']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run:  bundle exec ruby test/run.rb
